t = int(input('Digite um número para eu fornecer sua tabuada:'))
t1 = t * 1
t2 = t * 2
t3 = t * 3
t4 = t * 4
t5 = t * 5
t6 = t * 6
t7 = t * 7
t8 = t * 8
t9 = t * 9
t10 = t * 10
#print('A tabuada do número {} é a seguinte: {},{},{},{},{},{},{},{},{},{}'.format(t,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10))
print('=' * 15)
print(f'{t} x {1} = {t1} ')
print(f'{t} x {2} = {t2} ')
print(f'{t} x {3} = {t3} ')
print(f'{t} x {4} = {t4} ')
print(f'{t} x {5} = {t5} ')
print(f'{t} x {6} = {t6} ')
print(f'{t} x {7} = {t7} ')
print(f'{t} x {8} = {t8} ')
print(f'{t} x {9} = {t9} ')
print(f'{t} x {10} = {t10}')
print('='* 15)